# S&P 500 constituents — symbol, name, sector
# Refresh periodically; index membership changes.
SP500 = [
("AAPL","Apple","Technology"),("MSFT","Microsoft","Technology"),("NVDA","NVIDIA","Technology"),
("AMZN","Amazon","Consumer Disc"),("GOOGL","Alphabet A","Communication"),("GOOG","Alphabet C","Communication"),
("META","Meta Platforms","Communication"),("BRK.B","Berkshire Hathaway","Financials"),
("AVGO","Broadcom","Technology"),("TSLA","Tesla","Consumer Disc"),("LLY","Eli Lilly","Healthcare"),
("JPM","JPMorgan Chase","Financials"),("WMT","Walmart","Consumer Staples"),("V","Visa","Financials"),
("XOM","Exxon Mobil","Energy"),("UNH","UnitedHealth","Healthcare"),("ORCL","Oracle","Technology"),
("MA","Mastercard","Financials"),("COST","Costco","Consumer Staples"),("HD","Home Depot","Consumer Disc"),
("PG","Procter & Gamble","Consumer Staples"),("JNJ","Johnson & Johnson","Healthcare"),
("NFLX","Netflix","Communication"),("ABBV","AbbVie","Healthcare"),("BAC","Bank of America","Financials"),
("CRM","Salesforce","Technology"),("CVX","Chevron","Energy"),("KO","Coca-Cola","Consumer Staples"),
("MRK","Merck","Healthcare"),("AMD","Advanced Micro Devices","Technology"),("PEP","PepsiCo","Consumer Staples"),
("TMO","Thermo Fisher","Healthcare"),("LIN","Linde","Materials"),("CSCO","Cisco","Technology"),
("ACN","Accenture","Technology"),("ADBE","Adobe","Technology"),("MCD","McDonald's","Consumer Disc"),
("WFC","Wells Fargo","Financials"),("ABT","Abbott Labs","Healthcare"),("GE","GE Aerospace","Industrials"),
("NOW","ServiceNow","Technology"),("IBM","IBM","Technology"),("QCOM","Qualcomm","Technology"),
("TXN","Texas Instruments","Technology"),("CAT","Caterpillar","Industrials"),("DHR","Danaher","Healthcare"),
("VZ","Verizon","Communication"),("INTU","Intuit","Technology"),("PM","Philip Morris","Consumer Staples"),
("ISRG","Intuitive Surgical","Healthcare"),("NEE","NextEra Energy","Utilities"),("RTX","RTX Corp","Industrials"),
("CMCSA","Comcast","Communication"),("SPGI","S&P Global","Financials"),("AMGN","Amgen","Healthcare"),
("UNP","Union Pacific","Industrials"),("PGR","Progressive","Financials"),("LOW","Lowe's","Consumer Disc"),
("HON","Honeywell","Industrials"),("T","AT&T","Communication"),("AXP","American Express","Financials"),
("MS","Morgan Stanley","Financials"),("BKNG","Booking Holdings","Consumer Disc"),("ETN","Eaton","Industrials"),
("BLK","BlackRock","Financials"),("SYK","Stryker","Healthcare"),("COP","ConocoPhillips","Energy"),
("VRTX","Vertex Pharma","Healthcare"),("TJX","TJX Companies","Consumer Disc"),("C","Citigroup","Financials"),
("SCHW","Charles Schwab","Financials"),("MU","Micron","Technology"),("BSX","Boston Scientific","Healthcare"),
("ADP","Automatic Data","Industrials"),("FI","Fiserv","Financials"),("GILD","Gilead Sciences","Healthcare"),
("DE","Deere","Industrials"),("PLD","Prologis","Real Estate"),("MDT","Medtronic","Healthcare"),
("LMT","Lockheed Martin","Industrials"),("BMY","Bristol-Myers","Healthcare"),("ADI","Analog Devices","Technology"),
("CB","Chubb","Financials"),("MMC","Marsh McLennan","Financials"),("SBUX","Starbucks","Consumer Disc"),
("AMT","American Tower","Real Estate"),("PANW","Palo Alto Networks","Technology"),("UPS","United Parcel","Industrials"),
("LRCX","Lam Research","Technology"),("KLAC","KLA Corp","Technology"),("SO","Southern Co","Utilities"),
("ICE","Intercontinental Exch","Financials"),("ELV","Elevance Health","Healthcare"),("NKE","Nike","Consumer Disc"),
("SHW","Sherwin-Williams","Materials"),("MO","Altria","Consumer Staples"),("DUK","Duke Energy","Utilities"),
("PH","Parker-Hannifin","Industrials"),("CI","Cigna","Healthcare"),("APH","Amphenol","Technology"),
("PYPL","PayPal","Financials"),("TT","Trane Technologies","Industrials"),("WM","Waste Management","Industrials"),
("CDNS","Cadence Design","Technology"),("MSI","Motorola Solutions","Technology"),("SNPS","Synopsys","Technology"),
("CME","CME Group","Financials"),("EQIX","Equinix","Real Estate"),("REGN","Regeneron","Healthcare"),
("ZTS","Zoetis","Healthcare"),("MCK","McKesson","Healthcare"),("CVS","CVS Health","Healthcare"),
("AON","Aon","Financials"),("CL","Colgate-Palmolive","Consumer Staples"),("ITW","Illinois Tool Works","Industrials"),
("GD","General Dynamics","Industrials"),("MDLZ","Mondelez","Consumer Staples"),("USB","US Bancorp","Financials"),
("EOG","EOG Resources","Energy"),("NOC","Northrop Grumman","Industrials"),("TDG","TransDigm","Industrials"),
("CSX","CSX Corp","Industrials"),("EMR","Emerson Electric","Industrials"),("MMM","3M","Industrials"),
("CTAS","Cintas","Industrials"),("SLB","Schlumberger","Energy"),("ORLY","O'Reilly Automotive","Consumer Disc"),
("MAR","Marriott","Consumer Disc"),("APD","Air Products","Materials"),("FCX","Freeport-McMoRan","Materials"),
("PNC","PNC Financial","Financials"),("BDX","Becton Dickinson","Healthcare"),("HCA","HCA Healthcare","Healthcare"),
("ROP","Roper Technologies","Technology"),("AJG","Arthur J Gallagher","Financials"),("NSC","Norfolk Southern","Industrials"),
("COF","Capital One","Financials"),("WELL","Welltower","Real Estate"),("TGT","Target","Consumer Staples"),
("CARR","Carrier Global","Industrials"),("PCAR","PACCAR","Industrials"),("AZO","AutoZone","Consumer Disc"),
("FDX","FedEx","Industrials"),("SPG","Simon Property","Real Estate"),("TFC","Truist Financial","Financials"),
("NXPI","NXP Semiconductors","Technology"),("AFL","Aflac","Financials"),("SRE","Sempra","Utilities"),
("MPC","Marathon Petroleum","Energy"),("PSX","Phillips 66","Energy"),("DLR","Digital Realty","Real Estate"),
("TRV","Travelers","Financials"),("O","Realty Income","Real Estate"),("AIG","American Intl Group","Financials"),
("MET","MetLife","Financials"),("ALL","Allstate","Financials"),("AEP","American Electric","Utilities"),
("GM","General Motors","Consumer Disc"),("F","Ford Motor","Consumer Disc"),("D","Dominion Energy","Utilities"),
("HLT","Hilton Worldwide","Consumer Disc"),("PSA","Public Storage","Real Estate"),("CPRT","Copart","Industrials"),
("URI","United Rentals","Industrials"),("KMB","Kimberly-Clark","Consumer Staples"),("OXY","Occidental Petro","Energy"),
("VLO","Valero Energy","Energy"),("PAYX","Paychex","Industrials"),("ROST","Ross Stores","Consumer Disc"),
("MCHP","Microchip Technology","Technology"),("STZ","Constellation Brands","Consumer Staples"),
("GIS","General Mills","Consumer Staples"),("MNST","Monster Beverage","Consumer Staples"),
("KMI","Kinder Morgan","Energy"),("WMB","Williams Companies","Energy"),("EXC","Exelon","Utilities"),
("IDXX","IDEXX Labs","Healthcare"),("CMI","Cummins","Industrials"),("KVUE","Kenvue","Consumer Staples"),
("DOW","Dow Inc","Materials"),("EW","Edwards Lifesciences","Healthcare"),("CCI","Crown Castle","Real Estate"),
("HUM","Humana","Healthcare"),("A","Agilent Technologies","Healthcare"),("YUM","Yum! Brands","Consumer Disc"),
("SYY","Sysco","Consumer Staples"),("VRSK","Verisk Analytics","Industrials"),("OTIS","Otis Worldwide","Industrials"),
("XEL","Xcel Energy","Utilities"),("PRU","Prudential Financial","Financials"),("HSY","Hershey","Consumer Staples"),
("ED","Consolidated Edison","Utilities"),("GEHC","GE HealthCare","Healthcare"),("CTSH","Cognizant","Technology"),
("BK","Bank of New York","Financials"),("FTNT","Fortinet","Technology"),("DD","DuPont","Materials"),
("RSG","Republic Services","Industrials"),("PEG","Public Service Ent","Utilities"),("EA","Electronic Arts","Communication"),
("ODFL","Old Dominion","Industrials"),("DHI","D.R. Horton","Consumer Disc"),("KR","Kroger","Consumer Staples"),
("VICI","VICI Properties","Real Estate"),("HES","Hess","Energy"),("IQV","IQVIA","Healthcare"),
("CSGP","CoStar Group","Real Estate"),("NUE","Nucor","Materials"),("EXR","Extra Space Storage","Real Estate"),
("WAB","Wabtec","Industrials"),("GWW","W.W. Grainger","Industrials"),("MTB","M&T Bank","Financials"),
("LEN","Lennar","Consumer Disc"),("EFX","Equifax","Industrials"),("DAL","Delta Air Lines","Industrials"),
("ON","ON Semiconductor","Technology"),("AME","AMETEK","Industrials"),("XYL","Xylem","Industrials"),
("FAST","Fastenal","Industrials"),("BKR","Baker Hughes","Energy"),("CBRE","CBRE Group","Real Estate"),
("ROK","Rockwell Automation","Industrials"),("CHTR","Charter Communications","Communication"),
("DXCM","DexCom","Healthcare"),("VMC","Vulcan Materials","Materials"),("MLM","Martin Marietta","Materials"),
("WTW","Willis Towers Watson","Financials"),("STT","State Street","Financials"),("TSCO","Tractor Supply","Consumer Disc"),
("GLW","Corning","Technology"),("FITB","Fifth Third Bancorp","Financials"),("AWK","American Water","Utilities"),
("ANSS","ANSYS","Technology"),("MPWR","Monolithic Power","Technology"),("PPG","PPG Industries","Materials"),
("KDP","Keurig Dr Pepper","Consumer Staples"),("HIG","Hartford Financial","Financials"),("WEC","WEC Energy","Utilities"),
("HPQ","HP Inc","Technology"),("EIX","Edison International","Utilities"),("KHC","Kraft Heinz","Consumer Staples"),
("TROW","T. Rowe Price","Financials"),("CDW","CDW Corp","Technology"),("NDAQ","Nasdaq Inc","Financials"),
("DVN","Devon Energy","Energy"),("TTWO","Take-Two Interactive","Communication"),("CAH","Cardinal Health","Healthcare"),
("BR","Broadridge","Industrials"),("ES","Eversource Energy","Utilities"),("CHD","Church & Dwight","Consumer Staples"),
("ADSK","Autodesk","Technology"),("LYB","LyondellBasell","Materials"),("RJF","Raymond James","Financials"),
("DFS","Discover Financial","Financials"),("ZBH","Zimmer Biomet","Healthcare"),("HAL","Halliburton","Energy"),
("WY","Weyerhaeuser","Real Estate"),("PHM","PulteGroup","Consumer Disc"),("STE","STERIS","Healthcare"),
("AVB","AvalonBay","Real Estate"),("SBAC","SBA Communications","Real Estate"),("NTAP","NetApp","Technology"),
("EQR","Equity Residential","Real Estate"),("MTD","Mettler-Toledo","Healthcare"),("ARE","Alexandria Real Est","Real Estate"),
("FANG","Diamondback Energy","Energy"),("BIIB","Biogen","Healthcare"),("ULTA","Ulta Beauty","Consumer Disc"),
("HBAN","Huntington Bancshares","Financials"),("PPL","PPL Corp","Utilities"),("CNP","CenterPoint Energy","Utilities"),
("WST","West Pharmaceutical","Healthcare"),("EBAY","eBay","Consumer Disc"),("VLTO","Veralto","Industrials"),
("LH","Labcorp","Healthcare"),("FE","FirstEnergy","Utilities"),("TDY","Teledyne","Technology"),
("STLD","Steel Dynamics","Materials"),("IFF","Intl Flavors","Materials"),("K","Kellanova","Consumer Staples"),
("DTE","DTE Energy","Utilities"),("WDC","Western Digital","Technology"),("CINF","Cincinnati Financial","Financials"),
("ATO","Atmos Energy","Utilities"),("DRI","Darden Restaurants","Consumer Disc"),("LDOS","Leidos","Industrials"),
("PFG","Principal Financial","Financials"),("CMS","CMS Energy","Utilities"),("CLX","Clorox","Consumer Staples"),
("WRB","W.R. Berkley","Financials"),("NTRS","Northern Trust","Financials"),("ESS","Essex Property","Real Estate"),
("EXPE","Expedia","Consumer Disc"),("CFG","Citizens Financial","Financials"),("MKC","McCormick","Consumer Staples"),
("HOLX","Hologic","Healthcare"),("BALL","Ball Corp","Materials"),("SNA","Snap-on","Industrials"),
("MAA","Mid-America Apt","Real Estate"),("OMC","Omnicom Group","Communication"),("TSN","Tyson Foods","Consumer Staples"),
("WAT","Waters Corp","Healthcare"),("KEY","KeyCorp","Financials"),("PKG","Packaging Corp","Materials"),
("J","Jacobs Solutions","Industrials"),("ZBRA","Zebra Technologies","Technology"),("AVY","Avery Dennison","Materials"),
("BAX","Baxter International","Healthcare"),("TXT","Textron","Industrials"),("IP","International Paper","Materials"),
("EG","Everest Group","Financials"),("MAS","Masco","Industrials"),("GEN","Gen Digital","Technology"),
("DGX","Quest Diagnostics","Healthcare"),("LUV","Southwest Airlines","Industrials"),("AKAM","Akamai","Technology"),
("SWKS","Skyworks Solutions","Technology"),("JBHT","J.B. Hunt","Industrials"),("VTR","Ventas","Real Estate"),
("EXPD","Expeditors Intl","Industrials"),("AMCR","Amcor","Materials"),("L","Loews","Financials"),
("POOL","Pool Corp","Consumer Disc"),("SWK","Stanley Black & Decker","Industrials"),("EVRG","Evergy","Utilities"),
("LNT","Alliant Energy","Utilities"),("NDSN","Nordson","Industrials"),("CAG","Conagra Brands","Consumer Staples"),
("UDR","UDR Inc","Real Estate"),("JKHY","Jack Henry","Financials"),("DOC","Healthpeak Properties","Real Estate"),
("KIM","Kimco Realty","Real Estate"),("INCY","Incyte","Healthcare"),("TER","Teradyne","Technology"),
("ALLE","Allegion","Industrials"),("REG","Regency Centers","Real Estate"),("BBY","Best Buy","Consumer Disc"),
("SJM","J.M. Smucker","Consumer Staples"),("CPT","Camden Property","Real Estate"),("EMN","Eastman Chemical","Materials"),
("ROL","Rollins","Industrials"),("PNR","Pentair","Industrials"),("UHS","Universal Health","Healthcare"),
("JNPR","Juniper Networks","Technology"),("NI","NiSource","Utilities"),("CE","Celanese","Materials"),
("TAP","Molson Coors","Consumer Staples"),("HST","Host Hotels","Real Estate"),("GL","Globe Life","Financials"),
("CHRW","C.H. Robinson","Industrials"),("AES","AES Corp","Utilities"),("BXP","BXP Inc","Real Estate"),
("APA","APA Corp","Energy"),("HSIC","Henry Schein","Healthcare"),("FRT","Federal Realty","Real Estate"),
("AOS","A.O. Smith","Industrials"),("MKTX","MarketAxess","Financials"),("IVZ","Invesco","Financials"),
("MOS","Mosaic","Materials"),("CTLT","Catalent","Healthcare"),("DAY","Dayforce","Technology"),
("PARA","Paramount Global","Communication"),("MHK","Mohawk Industries","Consumer Disc"),
("BEN","Franklin Resources","Financials"),("HAS","Hasbro","Consumer Disc"),("WBA","Walgreens Boots","Consumer Staples"),
("NWSA","News Corp A","Communication"),("FOXA","Fox Corp A","Communication"),("DVA","DaVita","Healthcare"),
("CZR","Caesars Entertainment","Consumer Disc"),("MGM","MGM Resorts","Consumer Disc"),("WYNN","Wynn Resorts","Consumer Disc"),
("RL","Ralph Lauren","Consumer Disc"),("NCLH","Norwegian Cruise","Consumer Disc"),("CCL","Carnival","Consumer Disc"),
("RCL","Royal Caribbean","Consumer Disc"),("UAL","United Airlines","Industrials"),("AAL","American Airlines","Industrials"),
("ETSY","Etsy","Consumer Disc"),("MTCH","Match Group","Communication"),("PINS","Pinterest","Communication"),
("ABNB","Airbnb","Consumer Disc"),("UBER","Uber Technologies","Industrials"),("DASH","DoorDash","Consumer Disc"),
("PLTR","Palantir","Technology"),("CRWD","CrowdStrike","Technology"),("DDOG","Datadog","Technology"),
("TEAM","Atlassian","Technology"),("WDAY","Workday","Technology"),("VRSN","VeriSign","Technology"),
("GDDY","GoDaddy","Technology"),("FSLR","First Solar","Technology"),("ENPH","Enphase Energy","Technology"),
("SMCI","Super Micro Computer","Technology"),("KKR","KKR & Co","Financials"),("BX","Blackstone","Financials"),
("APO","Apollo Global","Financials"),("ARES","Ares Management","Financials"),("COIN","Coinbase","Financials"),
("HOOD","Robinhood","Financials"),("SOLV","Solventum","Healthcare"),("GEV","GE Vernova","Industrials"),
("VST","Vistra","Utilities"),("CEG","Constellation Energy","Utilities"),("TRGP","Targa Resources","Energy"),
("EQT","EQT Corp","Energy"),("CTRA","Coterra Energy","Energy"),("MRNA","Moderna","Healthcare"),
("ALGN","Align Technology","Healthcare"),("PODD","Insulet","Healthcare"),("RVTY","Revvity","Healthcare"),
("TECH","Bio-Techne","Healthcare"),("CRL","Charles River Labs","Healthcare"),("BIO","Bio-Rad Labs","Healthcare"),
("LW","Lamb Weston","Consumer Staples"),("BF.B","Brown-Forman","Consumer Staples"),("EL","Estee Lauder","Consumer Staples"),
("BG","Bunge Global","Consumer Staples"),("ADM","Archer-Daniels","Consumer Staples"),("DPZ","Domino's Pizza","Consumer Disc"),
("CMG","Chipotle","Consumer Disc"),("LULU","Lululemon","Consumer Disc"),("DECK","Deckers Outdoor","Consumer Disc"),
("NVR","NVR Inc","Consumer Disc"),("GRMN","Garmin","Consumer Disc"),("APTV","Aptiv","Consumer Disc"),
("BWA","BorgWarner","Consumer Disc"),("LKQ","LKQ Corp","Consumer Disc"),("GPC","Genuine Parts","Consumer Disc"),
("KMX","CarMax","Consumer Disc"),("TPR","Tapestry","Consumer Disc"),("IPG","Interpublic Group","Communication"),
("LYV","Live Nation","Communication"),("WBD","Warner Bros Discovery","Communication"),("DIS","Walt Disney","Communication"),
("BA","Boeing","Industrials"),("LHX","L3Harris","Industrials"),("HWM","Howmet Aerospace","Industrials"),
("HII","Huntington Ingalls","Industrials"),("IR","Ingersoll Rand","Industrials"),("DOV","Dover Corp","Industrials"),
("FTV","Fortive","Industrials"),("IEX","IDEX Corp","Industrials"),("GNRC","Generac","Industrials"),
("BLDR","Builders FirstSource","Industrials"),("PWR","Quanta Services","Industrials"),("ACGL","Arch Capital","Financials"),
("SYF","Synchrony Financial","Financials"),("AIZ","Assurant","Financials"),("BRO","Brown & Brown","Financials"),
("ERIE","Erie Indemnity","Financials"),("FDS","FactSet","Financials"),("MSCI","MSCI Inc","Financials"),
("MCO","Moody's","Financials"),("CBOE","Cboe Global Markets","Financials"),("SEIC","SEI Investments","Financials"),
("RF","Regions Financial","Financials"),("ZION","Zions Bancorp","Financials"),("CMA","Comerica","Financials"),
("FFIV","F5 Inc","Technology"),("EPAM","EPAM Systems","Technology"),("IT","Gartner","Technology"),
("PTC","PTC Inc","Technology"),("TYL","Tyler Technologies","Technology"),("KEYS","Keysight","Technology"),
("TRMB","Trimble","Technology"),("STX","Seagate Technology","Technology"),("JBL","Jabil","Technology"),
("VTRS","Viatris","Healthcare"),("MRO","Marathon Oil","Energy"),("OKE","ONEOK","Energy"),
("PCG","PG&E Corp","Utilities"),("NRG","NRG Energy","Utilities"),("AEE","Ameren","Utilities"),
("CNC","Centene","Healthcare"),("MOH","Molina Healthcare","Healthcare"),("COR","Cencora","Healthcare"),
("NEM","Newmont","Materials"),("CF","CF Industries","Materials"),("ALB","Albemarle","Materials"),
("SW","Smurfit Westrock","Materials"),("CPB","Campbell's","Consumer Staples"),("DG","Dollar General","Consumer Staples"),
("DLTR","Dollar Tree","Consumer Staples"),("SOLV","Solventum","Healthcare"),("NWS","News Corp B","Communication"),
]
# de-dupe, keep order
_seen=set(); SP500=[x for x in SP500 if not (x[0] in _seen or _seen.add(x[0]))]

# ETFs prepended so benchmarks are always available
ETFS = [("SPY","S&P 500 ETF","Index"),("QQQ","Nasdaq 100 ETF","Index"),
        ("DIA","Dow 30 ETF","Index"),("IWM","Russell 2000 ETF","Index"),
        ("VTI","Total US Market ETF","Index"),("GLD","Gold ETF","Commodity"),
        ("SLV","Silver ETF","Commodity"),("USO","Crude Oil ETF","Commodity"),
        ("TLT","20+ Year Treasury ETF","Rates"),("HYG","High Yield Bond ETF","Rates")]

UNIVERSE = ETFS + SP500
